{
 "title": "MySQL 8.0 Overview",
 "description": "Dashboard for MySQL Monitoring from prometheus mysql exporter.",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "project", "label": "project", "query": { "query": "label_values(project)" } },
   { "name": "desc", "label": "desc", "query": { "query": "label_values(desc)" } },
   {
    "name": "interval",
    "label": "interval",
    "query": "2m, 5m, 10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Command Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MySQL Connected",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected{desc=\"$desc\", project=\"$project\"}",
     "legendFormat": "Connected"
    }
   ]
  },
  {
   "title": "Select Command",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\", project=\"$project\", desc=\"$desc\"}[$__interval])",
     "legendFormat": "Select"
    }
   ]
  },
  {
   "title": "Update Command",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"update\", project=\"$project\", desc=\"$desc\"}[$__interval])",
     "legendFormat": "Update"
    }
   ]
  },
  {
   "title": "Insert Command",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"insert\", project=\"$project\", desc=\"$desc\"}[$__interval])",
     "legendFormat": "Update"
    }
   ]
  },
  {
   "title": "Delete Command",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"delete\", project=\"$project\", desc=\"$desc\"}[$__interval])",
     "legendFormat": "Delete"
    }
   ]
  },
  {
   "title": "System Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime - $desc",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{desc=\"$desc\",project=\"$project\",job=\"node\"}"
    }
   ]
  },
  {
   "title": "CPU Usage - $desc",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg by (instance, mode) (irate(node_cpu_seconds_total{desc=\"$desc\",project=\"$project\", mode=~\"system|user|nice|interrupt|iowait|irq|softirq|steel\"}[$interval])) * 100)",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Memory - $desc",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{project=\"$project\",desc=\"$desc\"} - (node_memory_Shmem_bytes{project=\"$project\",desc=\"$desc\"} + node_memory_Buffers_bytes{project=\"$project\",desc=\"$desc\"} + node_memory_Cached_bytes{project=\"$project\",desc=\"$desc\"} + node_memory_MemFree_bytes{project=\"$project\",desc=\"$desc\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{project=\"$project\",desc=\"$desc\"}",
     "legendFormat": "Buffered"
    },
    {
     "expr": "node_memory_Cached_bytes{project=\"$project\",desc=\"$desc\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{project=\"$project\",desc=\"$desc\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Load Average - $desc",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{desc=\"$desc\",project=\"$project\"}",
     "legendFormat": "1 Minute Average"
    },
    {
     "expr": "node_load5{desc=\"$desc\",project=\"$project\"}",
     "legendFormat": "5 Minute Average"
    },
    {
     "expr": "node_load15{desc=\"$desc\",project=\"$project\"}",
     "legendFormat": "15 Minute Average"
    }
   ]
  },
  {
   "title": "Traffic - $desc",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"eth0\",desc=\"$desc\",project=\"$project\"}[$interval])",
     "legendFormat": "InBound"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device=\"eth0\",desc=\"$desc\",project=\"$project\"}[2m])",
     "legendFormat": "OutBound"
    }
   ]
  },
  {
   "title": "Netstat - $desc",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_tcp_connection_states{desc=\"$desc\",project=\"$project\", state!~\".*queued_bytes$\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Disk I/O - $desc",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{desc=\"$desc\",device=\"vda2\",project=\"$project\"}[2m])",
     "legendFormat": "Read(/dev/sdb)"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{desc=\"$desc\",device=\"vda2\",project=\"$project\"}[2m])",
     "legendFormat": "Read(/dev/sdc)"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{desc=\"$desc\",device=\"vda2\",project=\"$project\"}[2m])",
     "legendFormat": "Write(/dev/sdb)"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{desc=\"$desc\",device=\"vda2\",project=\"$project\"}[2m])",
     "legendFormat": "Write(/dev/sdc)"
    }
   ]
  },
  {
   "title": "Node Disk I/O",
   "type": "timeseries",
   "description": "Disk I/O includes read or write or input/output operations involving a physical disk. It is the speed with which the data transfer takes place between the hard disk drive and RAM.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "avg by (desc) (rate(mysql_global_status_innodb_data_reads{desc=\"$desc\",project=\"$project\"}[$__interval]) or irate(mysql_global_status_innodb_data_reads{desc=\"$desc\",project=\"$project\"}[5m]))",
     "legendFormat": "Data Reads (Page In)"
    },
    {
     "expr": "avg by (node_name) ((rate(node_vmstat_pgpgout{desc=\"$desc\",project=\"$project\"}[$__interval]) * 1024 or irate(node_vmstat_pgpgout{desc=\"$desc\",project=\"$project\"}[5m]) * 1024))",
     "legendFormat": "Disk Writes (Page Out)"
    },
    {
     "expr": "avg by (node_name) ((rate(node_vmstat_pgpgin{desc=\"$desc\",project=\"$project\"}[$__interval]) * 1024 or irate(node_vmstat_pgpgin{desc=\"$desc\",project=\"$project\"}[5m]) * 1024 ) + (rate(node_vmstat_pgpgout{desc=\"$desc\",project=\"$project\"}[$__interval]) * 1024 or irate(node_vmstat_pgpgout{desc=\"$desc\",project=\"$project\"}[5m]) * 1024))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Node Disk I/O Load",
   "type": "timeseries",
   "description": "Shows how much disk was loaded for reads or writes as average number of outstanding requests at different period of time.  High disk load is a good measure of actual storage utilization. Different storage types handle load differently - some will show latency increases on low loads others can handle higher load with no problems.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (node_name) (sum(rate(node_disk_read_time_seconds_total{desc=\"$desc\",project=\"$project\"}[$__interval])) or sum(irate(node_disk_read_time_seconds_total{desc=\"$desc\",project=\"$project\"}[5m])) or (sum(rdsosmetrics_diskIO_readIOsPS{desc=\"$desc\",project=\"$project\"})))",
     "legendFormat": "Read Load"
    },
    {
     "expr": "avg by (node_name) (sum(rate(node_disk_write_time_seconds_total{desc=\"$desc\",project=\"$project\"}[$__interval])) or sum(irate(node_disk_write_time_seconds_total{desc=\"$desc\",project=\"$project\"}[5m])) or (sum(rdsosmetrics_diskIO_writeIOsPS{desc=\"$desc\",project=\"$project\"})))",
     "legendFormat": "Write Load"
    },
    {
     "expr": "avg by (node_name) ((sum(rate(node_disk_read_time_seconds_total{desc=\"$desc\",project=\"$project\"}[$__interval])) or sum(irate(node_disk_read_time_seconds_total{desc=\"$desc\",project=\"$project\"}[5m]))) + (sum(rate(node_disk_write_time_seconds_total{desc=\"$desc\",project=\"$project\"}[$__interval])) or sum(irate(node_disk_write_time_seconds_total{desc=\"$desc\",project=\"$project\"}[5m]))) or (sum(rdsosmetrics_diskIO_writeIOsPS{desc=\"$desc\",project=\"$project\"})) +  (sum(rdsosmetrics_diskIO_readIOsPS{desc=\"$desc\",project=\"$project\"})))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Node Disk IO Latency",
   "type": "timeseries",
   "description": "Shows average latency for Reads and Writes IO Devices.  Higher than typical latency for highly loaded storage indicates saturation (overload) and is frequent cause of performance problems.  Higher than normal latency also can indicate internal storage problems.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (node_name) ((sum(rate(node_disk_read_time_seconds_total{desc=\"$desc\",project=\"$project\"}[$__interval])) / sum(rate(node_disk_reads_completed_total{desc=\"$desc\",project=\"$project\"}[$__interval]) > 0 )) or (sum(irate(node_disk_read_time_seconds_total{desc=\"$desc\",project=\"$project\"}[5m])) / sum(irate(node_disk_reads_completed_total{desc=\"$desc\",project=\"$project\"}[5m]) > 0 )) or avg_over_time(aws_rds_read_latency_average{desc=\"$desc\",project=\"$project\"}[$__interval])/1000 or avg_over_time(aws_rds_read_latency_average{desc=\"$desc\",project=\"$project\"}[5m])/1000 or avg_over_time(rdsosmetrics_diskIO_readLatency{desc=\"$desc\",project=\"$project\"}[$__interval])/1000 or avg_over_time(rdsosmetrics_diskIO_readLatency{desc=\"$desc\",project=\"$project\"}[5m])/1000)",
     "legendFormat": "Read Latency"
    },
    {
     "expr": "avg by (node_name) ((sum(rate(node_disk_write_time_seconds_total{desc=\"$desc\",project=\"$project\"}[$__interval])) / sum(rate(node_disk_writes_completed_total{desc=\"$desc\",project=\"$project\"}[$__interval]) > 0 )) or (sum(irate(node_disk_write_time_seconds_total{desc=\"$desc\",project=\"$project\"}[5m])) /  sum(irate(node_disk_writes_completed_total{desc=\"$desc\",project=\"$project\"}[5m]) > 0 )) or (avg_over_time(aws_rds_write_latency_average{desc=\"$desc\",project=\"$project\"}[$__interval])/1000 or avg_over_time(aws_rds_write_latency_average{desc=\"$desc\",project=\"$project\"}[5m])/1000) or (avg_over_time(rdsosmetrics_diskIO_writeLatency{desc=\"$desc\",project=\"$project\"}[$__interval]) or avg_over_time(rdsosmetrics_diskIO_writeLatency{desc=\"$desc\",project=\"$project\"}[5m]))/1000)",
     "legendFormat": "Write Latency"
    },
    {
     "expr": "avg by (node_name) ((sum(rate(node_disk_read_time_seconds_total{desc=\"$desc\",project=\"$project\"}[1h])) / sum(rate(node_disk_reads_completed_total{desc=\"$desc\",project=\"$project\"}[1h]) > 0 )) or avg_over_time(aws_rds_read_latency_average{desc=\"$desc\",project=\"$project\"}[1h])/1000 or avg_over_time(aws_rds_read_latency_average{desc=\"$desc\",project=\"$project\"}[1h])/1000 or avg_over_time(rdsosmetrics_diskIO_readLatency{desc=\"$desc\",project=\"$project\"}[1h])/1000 or avg_over_time(rdsosmetrics_diskIO_readLatency{desc=\"$desc\",project=\"$project\"}[1h])/1000)",
     "legendFormat": "Avg Read Latency (1h)"
    },
    {
     "expr": "avg by (node_name) ((sum(rate(node_disk_write_time_seconds_total{desc=\"$desc\",project=\"$project\"}[1h])) / sum(rate(node_disk_writes_completed_total{desc=\"$desc\",project=\"$project\"}[1h]) > 0 ))  or (avg_over_time(aws_rds_write_latency_average{desc=\"$desc\",project=\"$project\"}[$__interval])/1000 or avg_over_time(aws_rds_write_latency_average{desc=\"$desc\",project=\"$project\"}[1h])/1000) or (avg_over_time(rdsosmetrics_diskIO_writeLatency{desc=\"$desc\",project=\"$project\"}[$__interval])/1000 or avg_over_time(rdsosmetrics_diskIO_writeLatency{desc=\"$desc\",project=\"$project\"}[1h])/1000))",
     "legendFormat": "Avg Write Latency (1h)"
    }
   ]
  },
  {
   "title": "MySQL Instance Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "MySQL Uptime - $desc",
   "type": "stat",
   "description": "**MySQL Uptime**",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_uptime{desc=\"$desc\",project=\"$project\"}"
    }
   ]
  },
  {
   "title": "MySQL Version - $desc",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "mysql_version_info{desc=\"$desc\",project=\"$project\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Current QPS - $desc",
   "type": "stat",
   "description": "**Current QPS**\n\nBased on the queries reported by MySQL's ``SHOW STATUS`` command, it is the number of statements executed by the server within the last second. This variable includes statements executed within stored programs, unlike the Questions variable. It does not count \n``COM_PING`` or ``COM_STATISTICS`` commands.",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries{desc=\"$desc\",project=\"$project\"}[$interval])"
    }
   ]
  },
  {
   "title": "QPS Respoectively (Top 5) - $desc",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, rate(mysql_global_status_commands_total{desc=\"$desc\",project=\"$project\"}[$interval])>0 or irate(mysql_global_status_commands_total{desc=\"$desc\",project=\"$project\"}[5m])>0)",
     "legendFormat": "Com_{{ command }}"
    }
   ]
  },
  {
   "title": "MySQL Network Traffic - $desc",
   "type": "timeseries",
   "description": "**MySQL Network Traffic**\n\nHere we can see how much network traffic is generated by MySQL. Outbound is network traffic sent from MySQL and Inbound is network traffic MySQL has received.",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_bytes_received{desc=\"$desc\",project=\"$project\"}[$interval]) or irate(mysql_global_status_bytes_received{desc=\"$desc\",project=\"$project\"}[$interval])",
     "legendFormat": "InBound"
    },
    {
     "expr": "0 - rate(mysql_global_status_bytes_sent{desc=\"$desc\",project=\"$project\"}[$interval]) or irate(mysql_global_status_bytes_sent{desc=\"$desc\",project=\"$project\"}[$interval])",
     "legendFormat": "OutBound"
    }
   ]
  },
  {
   "title": "Aborted Connects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 49 },
   "targets": [
    {
     "expr": "irate(mysql_global_status_aborted_clients{desc=\"$desc\",project=\"$project\"}[$interval])",
     "legendFormat": "Abort Clients"
    },
    {
     "expr": "irate(mysql_global_status_aborted_connects{desc=\"$desc\",project=\"$project\"}[$interval])",
     "legendFormat": "Aborted Connects"
    }
   ]
  },
  {
   "title": "MySQL Client Thread Activity - $desc",
   "type": "timeseries",
   "description": "**MySQL Active Threads**\n\nThreads Connected is the number of open connections, while Threads Running is the number of threads not sleeping.",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(mysql_global_status_threads_connected{desc=\"$desc\",project=\"$project\"}[$interval])",
     "legendFormat": "Peak Threads Connected"
    },
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(mysql_global_status_threads_running{desc=\"$desc\",project=\"$project\"}[$interval])",
     "legendFormat": "Peak Threads Running"
    },
    {
     "expr": "avg_over_time(mysql_global_status_threads_running{desc=\"$desc\",project=\"$project\"}[$interval])",
     "legendFormat": "Avg Threads Running"
    }
   ]
  },
  {
   "title": "Threads Status - $desc",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_threads_cached{desc=\"$desc\",project=\"$project\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "mysql_global_status_threads_connected{desc=\"$desc\",project=\"$project\"}",
     "legendFormat": "Connected"
    },
    {
     "expr": "mysql_global_status_threads_created{desc=\"$desc\",project=\"$project\"}",
     "legendFormat": "Created"
    },
    {
     "expr": "mysql_global_status_threads_running{desc=\"$desc\",project=\"$project\"}",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Open Tables - $desc",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_open_tables{desc=\"$desc\",project=\"$project\"}"
    }
   ]
  },
  {
   "title": "Open Files - $desc",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_open_files{desc=\"$desc\",project=\"$project\"}"
    }
   ]
  },
  {
   "title": "Cache Miss Rate(%)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(mysql_global_status_threads_created{desc=\"$desc\",project=\"$project\"}[$interval])/max_over_time(mysql_global_status_connections{desc=\"$desc\",project=\"$project\"}[$interval])) * 100.0"
    }
   ]
  },
  {
   "title": "Connection Miss Rate(%)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(mysql_global_status_aborted_connects{desc=\"$desc\",project=\"$project\"}[$interval])/max_over_time(mysql_global_status_connections{desc=\"$desc\",project=\"$project\"}[$interval])) * 100.0"
    }
   ]
  },
  {
   "title": "Connection Usage(%)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(irate(mysql_global_status_connections{desc=\"$desc\",project=\"$project\"}[$interval])/mysql_global_variables_max_connections{desc=\"$desc\",project=\"$project\"}) * 100.0"
    }
   ]
  },
  {
   "title": "Process States",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (desc,state) (max_over_time(mysql_info_schema_processlist_threads{desc=\"$desc\",project=\"$project\"}[$__interval]) or max_over_time(mysql_info_schema_processlist_threads{desc=\"$desc\",project=\"$project\"}[5m]))",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Table Open Cache - $desc",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(mysql_global_status_opened_tables{desc=\"$desc\",project=\"$project\"}[$interval])",
     "legendFormat": "Opening"
    },
    {
     "expr": "irate(mysql_global_status_table_open_cache_hits{desc=\"$desc\",project=\"$project\"}[$interval])",
     "legendFormat": "Cache Hits"
    },
    {
     "expr": "irate(mysql_global_status_table_open_cache_misses{desc=\"$desc\",project=\"$project\"}[$interval])",
     "legendFormat": "Cache Misses"
    }
   ]
  },
  {
   "title": "Table Locks - $desc",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 57 },
   "targets": [
    {
     "expr": "irate(mysql_global_status_table_locks_immediate{desc=\"$desc\",project=\"$project\"}[$interval])",
     "legendFormat": "Table locks immediate"
    },
    {
     "expr": "irate(mysql_global_status_table_locks_waited{desc=\"$desc\",project=\"$project\"}[$interval])",
     "legendFormat": "Table locks waited"
    }
   ]
  },
  {
   "title": "Select Type - $desc",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(mysql_global_status_select_scan{desc=\"$desc\",project=\"$project\"}[$interval])",
     "legendFormat": "Select Scan"
    },
    {
     "expr": "irate(mysql_global_status_select_full_join{desc=\"$desc\",project=\"$project\"}[$interval])",
     "legendFormat": "Select Full Join"
    },
    {
     "expr": "irate(mysql_global_status_select_full_range_join{desc=\"$desc\",project=\"$project\"}[$interval])",
     "legendFormat": "Select Full Range Join"
    },
    {
     "expr": "irate(mysql_global_status_select_range{desc=\"$desc\",project=\"$project\"}[$interval])",
     "legendFormat": "Select Range"
    },
    {
     "expr": "irate(mysql_global_status_select_range_check{desc=\"$desc\",project=\"$project\"}[$interval])",
     "legendFormat": "Select Range Check"
    }
   ]
  },
  {
   "title": "Sort - $desc",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(mysql_global_status_sort_rows{desc=\"$desc\",project=\"$project\"}[$interval])",
     "legendFormat": "Sort Rows"
    },
    {
     "expr": "irate(mysql_global_status_sort_scan{desc=\"$desc\",project=\"$project\"}[$interval])",
     "legendFormat": "Sort Scan"
    },
    {
     "expr": "irate(mysql_global_status_sort_merge_passes{desc=\"$desc\",project=\"$project\"}[$interval])",
     "legendFormat": "Sort Merge Passes"
    },
    {
     "expr": "irate(mysql_global_status_sort_range{desc=\"$desc\",project=\"$project\"}[$interval])",
     "legendFormat": "Sort Range"
    }
   ]
  },
  {
   "title": "Temporary Object - $desc",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(mysql_global_status_created_tmp_tables{desc=\"$desc\",project=\"$project\"}[$interval])",
     "legendFormat": "Created tmp tables"
    },
    {
     "expr": "irate(mysql_global_status_created_tmp_disk_tables{desc=\"$desc\",project=\"$project\"}[$interval])",
     "legendFormat": "Created tmp disk tables"
    },
    {
     "expr": "irate(mysql_global_status_created_tmp_files{desc=\"$desc\",project=\"$project\"}[$interval])",
     "legendFormat": "Created tmp files"
    }
   ]
  },
  {
   "title": "Transactional Handlers - $desc",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(mysql_global_status_handlers_total{desc=\"$desc\",project=\"$project\",handler=~\"commit|prepare|rollback|savepoint|savepoint_rollback\"}[$interval])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Handlers - $desc",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(mysql_global_status_handlers_total{desc=\"$desc\",project=\"$project\",handler!~\"commit|prepare|rollback|savepoint|savepoint_rollback\"}[$interval]) > 0",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Binlog Cache - $desc",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(mysql_global_status_binlog_cache_use{desc=\"$desc\",project=\"$project\"}[$interval])",
     "legendFormat": "Binlog cache use"
    },
    {
     "expr": "irate(mysql_global_status_binlog_cache_disk_use{desc=\"$desc\",project=\"$project\"}[$interval])",
     "legendFormat": "Binlog cache disk use"
    },
    {
     "expr": "irate(mysql_global_status_binlog_stmt_cache_disk_use{desc=\"$desc\",project=\"$project\"}[$interval])",
     "legendFormat": "Binlog stmt cache disk use"
    }
   ]
  },
  {
   "title": "Memory Statistic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {}
   ]
  },
  {
   "title": "MySQL Internal Memory Overview",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (desc) (max_over_time(node_memory_MemTotal_bytes{project=\"$poejct\", desc=\"$desc\"}[$__interval]) or max_over_time(node_memory_MemTotal_bytes{project=\"$project\", desc=\"$desc\"}[5m]))",
     "legendFormat": "System Memory"
    },
    {
     "expr": "avg by (desc) (mysql_global_variables_innodb_buffer_pool_size{project=\"$project\", desc=\"$desc\"})",
     "legendFormat": "InnoDB Buffer Pool Size"
    },
    {
     "expr": "avg by (desc) (max_over_time(mysql_global_variables_innodb_log_buffer_size{project=\"$project\", desc=\"$desc\"}[$__interval]) or max_over_time(mysql_global_variables_innodb_log_buffer_size{project=\"$project\", desc=\"$desc\"}[5m]))",
     "legendFormat": "InnoDB Log Buffer Size"
    },
    {
     "expr": "avg by (desc) (max_over_time(mysql_global_variables_additional_mem_pool_size{project=\"$project\", desc=\"$desc\"}[$__interval]) or max_over_time(mysql_global_variables_additional_mem_pool_size{project=\"$project\", desc=\"$desc\"}[5m]))",
     "legendFormat": "InnoDB Additional Memory Pool Size"
    },
    {
     "expr": "avg by (desc) (max_over_time(mysql_global_status_innodb_mem_dictionary{project=\"$project\", desc=\"$desc\"}[$__interval]) or max_over_time(mysql_global_status_innodb_mem_dictionary{project=\"$project\", desc=\"$desc\"}[5m]))",
     "legendFormat": "InnoDB Dictionary Size"
    },
    {
     "expr": "avg by (desc) (max_over_time(mysql_global_variables_key_buffer_size{project=\"$project\", desc=\"$desc\"}[$__interval]) or max_over_time(mysql_global_variables_key_buffer_size{project=\"$project\", desc=\"$desc\"}[5m]))",
     "legendFormat": "Key Buffer Size"
    },
    {
     "expr": "avg by (desc) (max_over_time(mysql_global_variables_query_cache_size{project=\"$project\", desc=\"$desc\"}[$__interval]) or max_over_time(mysql_global_variables_query_cache_size{project=\"$project\", desc=\"$desc\"}[5m]))",
     "legendFormat": "Query Cache Size"
    },
    {
     "expr": "avg by (desc) (max_over_time(mysql_global_status_innodb_mem_adaptive_hash{project=\"$project\", desc=\"$desc\"}[$__interval]) or max_over_time(mysql_global_status_innodb_mem_adaptive_hash{project=\"$project\", desc=\"$desc\"}[5m]))",
     "legendFormat": "Adaptive Hash Index Size"
    },
    {
     "expr": "avg by (desc) (max_over_time(mysql_global_variables_tokudb_cache_size{project=\"$project\", desc=\"$desc\"}[$__interval]) or max_over_time(mysql_global_variables_tokudb_cache_size{project=\"$project\", desc=\"$desc\"}[5m]))",
     "legendFormat": "TokuDB Cache Size"
    }
   ]
  },
  {
   "title": "InnoDB Pool Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_innodb_buffer_pool_size{desc=\"$desc\",project=\"$project\"}"
    }
   ]
  },
  {
   "title": "BP Size of Total RAM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (desc) ((mysql_global_variables_innodb_buffer_pool_size{desc=\"$desc\",project=\"$project\"} * 100)) / on (node_name) (max by () (node_memory_MemTotal_bytes{desc=\"$desc\", project=\"$project\"}))"
    }
   ]
  },
  {
   "title": "InnoDB Old Blocks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (desc) (mysql_global_variables_innodb_old_blocks_pct{desc=\"$desc\",project=\"$project\"})"
    }
   ]
  },
  {
   "title": "Key Buffer Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_key_buffer_size{desc=\"$desc\",project=\"$project\"}"
    }
   ]
  },
  {
   "title": "InnoDB Log Buffer Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_innodb_log_buffer_size{desc=\"$desc\",project=\"$project\"}"
    }
   ]
  },
  {
   "title": "InnoDB Sort Buffer Size",
   "type": "stat",
   "description": "This Buffer is used for Buidling InnoDB Indexes using Sort algorithm",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (desc) (mysql_global_variables_innodb_sort_buffer_size{desc=\"$desc\",project=\"$project\"})"
    }
   ]
  },
  {
   "title": "BP Usage(%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_buffer_pool_pages{desc=\"$desc\",project=\"$project\",state=\"data\"} / on (instance) (mysql_global_status_buffer_pool_pages{desc=\"$desc\",project=\"$project\",state=\"data\"} + on (instance) mysql_global_status_buffer_pool_pages{desc=\"$desc\",project=\"$project\",state=\"free\"} + on (instance) mysql_global_status_buffer_pool_pages{desc=\"$desc\",project=\"$project\",state=\"misc\"}) * 100.0"
    }
   ]
  },
  {
   "title": "BP Write Activity",
   "type": "stat",
   "description": "Combined value of Buffer Pool Read and Write requests",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (desc) (irate(mysql_global_status_innodb_buffer_pool_write_requests{desc=\"$desc\",project=\"$project\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Data Buffer Pool Fit",
   "type": "stat",
   "description": "Buffer Pool Size as Portion of the Data",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mysql_global_variables_innodb_buffer_pool_size{project=\"$project\", desc=\"$desc\"})/sum(count(mysql_info_schema_table_version{project=\"$project\", desc=\"$desc\",engine=\"InnoDB\"}) by (schema,table) * sum (mysql_info_schema_table_size{project=\"$project\", desc=\"$desc\",component=~\"data_length|index_length\"}) by (schema,table))"
    }
   ]
  },
  {
   "title": "Buffer Pool Miss Ratio",
   "type": "stat",
   "description": "How often buffer pool read requests have to do read from the disk. Keep this percent low for good performance",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (desc) (irate(mysql_global_status_innodb_buffer_pool_reads{desc=\"$desc\",project=\"$project\"}[$interval])/irate(mysql_global_status_innodb_buffer_pool_read_requests{desc=\"$desc\", project=\"$project\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Indexing Overhead",
   "type": "stat",
   "description": "How Much Indexes Take Compared to Data",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(count(mysql_info_schema_table_version{project=\"$project\", desc=\"$desc\",engine=\"InnoDB\"}) by (schema,table) * sum (mysql_info_schema_table_size{project=\"$project\", desc=\"$desc\",component=\"index_length\"}) by (schema,table)))/(sum(count(mysql_info_schema_table_version{project=\"$project\", desc=\"$desc\", engine=\"InnoDB\"}) by (schema,table) * sum (mysql_info_schema_table_size{project=\"$project\", desc=\"$desc\",component=\"data_length\"}) by (schema,table)))"
    }
   ]
  },
  {
   "title": "InnoDB Tables",
   "type": "stat",
   "description": "Current Number of InnoDB Tables in database",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mysql_info_schema_table_version{project=\"$project\", desc=\"$desc\",engine=\"InnoDB\"})"
    }
   ]
  },
  {
   "title": "InnoDB Open Files",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_info_schema_innodb_metrics_file_system_file_num_open_files{desc=\"$desc\",project=\"$project\"}"
    }
   ]
  },
  {
   "title": "InnoDB File Per Table",
   "type": "stat",
   "description": "If Enabled, By Default every Table will have its own Tablespace represented as its own .idb file  rather than all tables stored in single system tablespace",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (mysql_global_variables_innodb_file_per_table{project=\"$project\", desc=\"$desc\"})"
    }
   ]
  },
  {
   "title": "Space Allocated",
   "type": "stat",
   "description": "Total Amount of Space Allocated.    May not exactly match amount of space used on file system but provided great guidance",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(mysql_info_schema_table_version{project=\"$project\", desc=\"$desc\",engine=\"InnoDB\"}) by (schema,table) * sum (mysql_info_schema_table_size{project=\"$project\", desc=\"$desc\"}) by (schema,table))"
    }
   ]
  },
  {
   "title": "Space Used",
   "type": "stat",
   "description": "Space used in All  InnoDB Tables.   Reported Allocated Space Less Free Space",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(mysql_info_schema_table_version{project=\"$project\", desc=\"$desc\",engine=\"InnoDB\"}) by (schema,table) * sum (mysql_info_schema_table_size{project=\"$project\", desc=\"$desc\",component=~\"data_length|index_length\"}) by (schema,table))"
    }
   ]
  },
  {
   "title": "Data Length",
   "type": "stat",
   "description": "Space Used by Data (Including Primary Key)",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(mysql_info_schema_table_version{project=\"$project\", desc=\"$desc\",engine=\"InnoDB\"}) by (schema,table) * sum (mysql_info_schema_table_size{project=\"$project\", desc=\"$desc\",component=\"data_length\"}) by (schema,table))"
    }
   ]
  },
  {
   "title": "Index Length",
   "type": "stat",
   "description": "Space Used by Secondary Indexes",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(mysql_info_schema_table_version{project=\"$project\", desc=\"$desc\",engine=\"InnoDB\"}) by (schema,table) * sum (mysql_info_schema_table_size{project=\"$project\", desc=\"$desc\",component=\"index_length\"}) by (schema,table))"
    }
   ]
  },
  {
   "title": "Free",
   "type": "stat",
   "description": "How Much Space is Free. Too high value wastes space on disk",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(mysql_info_schema_table_version{project=\"$project\", desc=\"$desc\",engine=\"InnoDB\"}) by (schema,table) * sum (mysql_info_schema_table_size{project=\"$project\", desc=\"$desc\",component=\"data_free\"}) by (schema,table))"
    }
   ]
  },
  {
   "title": "Estimated Rows",
   "type": "stat",
   "description": "Estimated number of Rows in InnoDB Storage Engine. It is not exact value and it can change abruptly as information is updated",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(mysql_info_schema_table_version{project=\"$project\", desc=\"$desc\",engine=\"InnoDB\"}) by (schema,table) * sum (mysql_info_schema_table_rows{project=\"$project\", desc=\"$desc\"}) by (schema,table))"
    }
   ]
  },
  {
   "title": "Data Size Per Row",
   "type": "stat",
   "description": "Amount of Data Per Row",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(mysql_info_schema_table_version{project=\"$project\", desc=\"$desc\",engine=\"InnoDB\"}) by (schema,table) * sum(mysql_info_schema_table_size{project=\"$project\", desc=\"$desc\",component=\"data_length\"}) by (schema,table)) / (sum(count(mysql_info_schema_table_version{project=\"$project\", desc=\"$desc\",engine=\"InnoDB\"}) by (schema,table) * sum (mysql_info_schema_table_rows{project=\"$project\", desc=\"$desc\"}) by (schema,table)))"
    }
   ]
  },
  {
   "title": "Index Size Per Row",
   "type": "stat",
   "description": "Index Size Per Row shows how much space we're using for indexes on per row basics",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(mysql_info_schema_table_version{project=\"$project\", desc=\"$desc\",engine=\"InnoDB\"}) by (schema,table) * sum(mysql_info_schema_table_size{project=\"$project\", desc=\"$desc\",component=\"index_length\"}) by (schema,table)) / (sum(count(mysql_info_schema_table_version{project=\"$project\", desc=\"$desc\",engine=\"InnoDB\"}) by (schema,table) * sum (mysql_info_schema_table_rows{project=\"$project\", desc=\"$desc\"}) by (schema,table)))"
    }
   ]
  },
  {
   "title": "Portion of Buffer Pool To Dump/Load",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * avg by (desc) (mysql_global_variables_innodb_buffer_pool_dump_pct{project=\"$project\", desc=\"$desc\"}/100)"
    }
   ]
  },
  {
   "title": "InnoDB Dedicated Server",
   "type": "stat",
   "description": "InnoDB automatically optimized for Dedicated Server Environment (auto scaling cache and some other variables)",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (desc) (mysql_global_variables_innodb_dedicated_server{desc=\"$desc\",project=\"$project\"})"
    }
   ]
  },
  {
   "title": "InnoDB Stats Auto Recalc",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (desc) (mysql_global_variables_innodb_stats_auto_recalc{desc=\"$desc\",project=\"$project\"})"
    }
   ]
  },
  {
   "title": "Update Stats when Metadata Queried",
   "type": "stat",
   "description": "Refresh InnoDB Statistics when meta-data queries by SHOW TABLE STATUS or INFORMATION_SCHEMA queries.  If Enabled can cause severe performance issues",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (desc) (mysql_global_variables_innodb_stats_on_metadata{desc=\"$desc\",project=\"$project\"})"
    }
   ]
  },
  {
   "title": "InnoDB Persistent Statistics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (desc) (mysql_global_variables_innodb_stats_persistent{desc=\"$desc\",project=\"$project\"})"
    }
   ]
  },
  {
   "title": "InnoDB Persistent Sample Pages",
   "type": "stat",
   "description": "Number of Pages To Sample if Persistent Statistics are Enabled",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (desc) (mysql_global_variables_innodb_stats_persistent_sample_pages{desc=\"$desc\",project=\"$project\"})"
    }
   ]
  },
  {
   "title": "InnoDB Transient Sample Pages",
   "type": "stat",
   "description": "Number of Pages To Sample if Persistent Statistics are Disabled",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (desc) (mysql_global_variables_innodb_stats_transient_sample_pages{desc=\"$desc\",project=\"$project\"})"
    }
   ]
  },
  { "title": "InnoDB Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "InnoDB Buffer Pool Pages",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (desc,state) (max_over_time(mysql_global_status_buffer_pool_pages{project=\"$project\", desc=\"$desc\", state=~\"free|data|misc\"}[$__interval]) or max_over_time(mysql_global_status_buffer_pool_pages{project=\"$project\", desc=\"$desc\", state=~\"free|data|misc\"}[5m]))",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Pages",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (desc) (avg_over_time(mysql_global_status_innodb_buffer_pool_bytes_data{project=\"$project\", desc=\"$desc\"}[$__interval]) or avg_over_time(mysql_global_status_innodb_buffer_pool_bytes_data{project=\"$project\", desc=\"$desc\"}[5m]))",
     "legendFormat": "Data Total"
    },
    {
     "expr": "avg by (desc) (avg_over_time(mysql_global_status_innodb_buffer_pool_bytes_dirty{project=\"$project\", desc=\"$desc\"}[$__interval]) or avg_over_time(mysql_global_status_innodb_buffer_pool_bytes_dirty{project=\"$project\", desc=\"$desc\"}[5m]))",
     "legendFormat": "Data Dirty"
    },
    {
     "expr": "avg by (desc) (sum((avg_over_time(mysql_global_status_innodb_buffer_pool_bytes_data{project=\"$project\", desc=\"$desc\"}[$__interval]) or avg_over_time(mysql_global_status_innodb_buffer_pool_bytes_data{project=\"$project\", desc=\"$desc\"}[5m])))*sum(mysql_global_variables_innodb_max_dirty_pages_pct{project=\"$project\", desc=\"$desc\"})/100)",
     "legendFormat": "Estimatred Dirty Data Limit"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Page Activity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (desc) (rate(mysql_global_status_innodb_pages_created{project=\"$project\", desc=\"$desc\"}[$__interval]) or irate(mysql_global_status_innodb_pages_created{project=\"$project\", desc=\"$desc\"}[5m]))",
     "legendFormat": "Pages Created"
    },
    {
     "expr": "avg by (desc) (rate(mysql_global_status_innodb_pages_read{project=\"$project\", desc=\"$desc\"}[$__interval]) or irate(mysql_global_status_innodb_pages_read{project=\"$project\", desc=\"$desc\"}[5m]))",
     "legendFormat": "Pages Read"
    },
    {
     "expr": "avg by (desc) (rate(mysql_global_status_innodb_pages_written{project=\"$project\", desc=\"$desc\"}[$__interval]) or irate(mysql_global_status_innodb_pages_written{project=\"$project\", desc=\"$desc\"}[5m]))",
     "legendFormat": "Pages Written"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (desc) (rate(mysql_global_status_innodb_buffer_pool_read_requests{project=\"$project\", desc=\"$desc\"}[$__interval]) or irate(mysql_global_status_innodb_buffer_pool_read_requests{project=\"$project\", desc=\"$desc\"}[5m]))",
     "legendFormat": "Read Requests"
    },
    {
     "expr": "avg by (desc) (rate(mysql_global_status_innodb_buffer_pool_write_requests{project=\"$project\", desc=\"$desc\"}[$__interval]) or irate(mysql_global_status_innodb_buffer_pool_write_requests{project=\"$project\", desc=\"$desc\"}[5m]))",
     "legendFormat": "Write Requests"
    }
   ]
  },
  {
   "title": "InnoDB Read-Ahead",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (desc) (rate(mysql_global_status_innodb_buffer_pool_read_ahead{project=\"$project\", desc=\"$desc\"}[$__interval]) or irate(mysql_global_status_innodb_buffer_pool_read_ahead{project=\"$project\", desc=\"$desc\"}[5m]))",
     "legendFormat": "Pages Fetched by Linear Read Ahead"
    },
    {
     "expr": "avg by (desc) (rate(mysql_global_status_innodb_buffer_pool_read_ahead_rnd{project=\"$project\", desc=\"$desc\"}[$__interval]) or irate(mysql_global_status_innodb_buffer_pool_read_ahead_rnd{project=\"$project\", desc=\"$desc\"}[5m]))",
     "legendFormat": "Paged Fetched by Random Read Ahead"
    },
    {
     "expr": "avg by (desc) (rate(mysql_global_status_innodb_buffer_pool_read_ahead_evicted{project=\"$project\", desc=\"$desc\"}[$__interval]) or irate(mysql_global_status_innodb_buffer_pool_read_ahead_evicted{project=\"$project\", desc=\"$desc\"}[5m]))",
     "legendFormat": "Paged Fetched by Read Ahead but Never Accessed"
    }
   ]
  },
  {
   "title": "InnoDB Activity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (desc) (rate(mysql_info_schema_innodb_metrics_server_innodb_activity_count_total{project=\"$project\",desc=\"$desc\"}[$__interval]) or irate(mysql_info_schema_innodb_metrics_server_innodb_activity_count_total{project=\"$project\",desc=\"$desc\"}[5m]))",
     "legendFormat": "InnoDB Activity"
    }
   ]
  },
  {
   "title": "InnoDB Row Reads",
   "type": "timeseries",
   "description": "**InnoDB Row Operations**\n\nThis graph allows you to see which operations occur and the number of rows affected per operation. A graph like Queries Per Second will give you an idea of queries, but one query could effect millions of rows.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (desc) (rate(mysql_global_status_innodb_row_ops_total{project=\"$project\", desc=\"$desc\",operation=\"read\"}[$__interval]) or irate(mysql_global_status_innodb_row_ops_total{desc=\"Systemv 그룹\",project=\"systemv_group\",operation=\"read\"}[5m]))",
     "legendFormat": "Rows {{ operation }}"
    }
   ]
  },
  {
   "title": "InnoDB Row Writes",
   "type": "timeseries",
   "description": "**InnoDB Row Operations**\n\nThis graph allows you to see which operations occur and the number of rows affected per operation. A graph like Queries Per Second will give you an idea of queries, but one query could effect millions of rows.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (desc,operation) (rate(mysql_global_status_innodb_row_ops_total{project=\"$project\", desc=\"$desc\",operation!=\"read\"}[$__interval]) or irate(mysql_global_status_innodb_row_ops_total{project=\"$project\", desc=\"$desc\",operation!=\"read\"}[5m]))",
     "legendFormat": "Rows {{ operation }}"
    }
   ]
  },
  { "title": "InnoDB Locking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 151 } },
  {
   "title": "Lock Wait Timeout",
   "type": "stat",
   "description": "** InnoDB Lock Wait Timeout **\nHow long to wait for row lock before timing out",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (desc) (mysql_global_variables_innodb_lock_wait_timeout{project=\"$project\", desc=\"$desc\"})"
    }
   ]
  },
  {
   "title": "InnoDB Deadlock Detection",
   "type": "stat",
   "description": "If Disabled InnoDB Will not detect deadlocks but rely on timeouts",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (desc) (mysql_global_variables_innodb_deadlock_detect{project=\"$project\", desc=\"$desc\"})"
    }
   ]
  },
  {
   "title": "InnoDB Auto Increment Lock Mode",
   "type": "stat",
   "description": "Will Define How mush locking will come from working with Auto Increment Columns",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (desc) (mysql_global_variables_innodb_deadlock_detect{project=\"$project\", desc=\"$desc\"})"
    }
   ]
  },
  {
   "title": "Rollback on Timeout",
   "type": "stat",
   "description": "Whenever to rollback all transaction on timeout or just last statement",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (mysql_global_variables_innodb_rollback_on_timeout{desc=\"$desc\",project=\"$project\"})"
    }
   ]
  },
  {
   "title": "Row Lock Blocking",
   "type": "stat",
   "description": "Percent of Active Sections which are blocked due to waiting on InnoDB Row Locks",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) ((rate(mysql_global_status_innodb_row_lock_time{desc=\"$desc\",project=\"$project\"}[$__interval])/1000 or irate(mysql_global_status_innodb_row_lock_time{desc=\"$desc\",project=\"$project\"}[5m])/1000)/((avg_over_time(mysql_global_status_threads_running{desc=\"$desc\",project=\"$project\"}[$__interval]))or (avg_over_time(mysql_global_status_threads_running{desc=\"$desc\",project=\"$project\"}[5m]))))"
    }
   ]
  },
  {
   "title": "InnoDB Row Lock Wait Activity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (desc) (rate(mysql_global_status_innodb_row_lock_waits{desc=\"$desc\",project=\"$project\"}[$__interval]) or irate(mysql_global_status_innodb_row_lock_waits{desc=\"$desc\",project=\"$project\"}[5m]))",
     "legendFormat": "Lock Waits"
    },
    {
     "expr": "avg by (desc) ((rate(mysql_global_status_innodb_deadlocks{desc=\"$desc\",project=\"$project\"}[$__interval]) or rate(mysql_info_schema_innodb_metrics_lock_lock_deadlocks_total{desc=\"$desc\",project=\"$project\"}[$__interval])) or (irate(mysql_global_status_innodb_deadlocks{desc=\"$desc\",project=\"$project\"}[5m]) or irate(mysql_info_schema_innodb_metrics_lock_lock_deadlocks_total{desc=\"$desc\",project=\"$project\"}[5m])))",
     "legendFormat": "Deadlocks"
    },
    {
     "expr": "avg by (desc) (rate(mysql_info_schema_innodb_metrics_lock_lock_timeouts_total{desc=\"$desc\",project=\"$project\"}[$__interval]) or irate(mysql_info_schema_innodb_metrics_lock_lock_timeouts_total{desc=\"$desc\",project=\"$project\"}[5m]))",
     "legendFormat": "Lock Wait Timeouts"
    }
   ]
  },
  {
   "title": "InnoDB Row Lock Wait Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_innodb_row_lock_time{desc=\"$desc\",project=\"$project\"}[$__interval])/rate(mysql_global_status_innodb_row_lock_waits{desc=\"$desc\",project=\"$project\"}[$__interval]) or irate(mysql_global_status_innodb_row_lock_time{desc=\"$desc\",project=\"$project\"}[5m])/irate(mysql_global_status_innodb_row_lock_waits{desc=\"$desc\",project=\"$project\"}[5m]))",
     "legendFormat": "Avg Row Lock Wait Time"
    }
   ]
  },
  {
   "title": "InnoDB Row Lock Wait Load",
   "type": "timeseries",
   "description": "Average Number of Sessions blocked from proceeding due to waiting on row level lock",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_innodb_row_lock_time{desc=\"$desc\",project=\"$project\"}[$__interval])/1000 or irate(mysql_global_status_innodb_row_lock_time{desc=\"$desc\",project=\"$project\"}[5m])/1000)",
     "legendFormat": "Row Lock Wait Load"
    },
    {
     "expr": "avg by (service_name) (((avg_over_time(mysql_global_status_threads_running{desc=\"$desc\",project=\"$project\"}[$__interval]))or (avg_over_time(mysql_global_status_threads_running{desc=\"$desc\",project=\"$project\"}[5m]))))",
     "legendFormat": "MySQL Threads Active"
    }
   ]
  },
  { "title": "InnoDB Disk IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 177 } },
  {
   "title": "InnoDB Page Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (desc) (mysql_global_status_innodb_page_size{desc=\"$desc\",project=\"$project\"})"
    }
   ]
  },
  {
   "title": "Avg Data Read Rq Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (desc) ((rate(mysql_global_status_innodb_data_read{desc=\"$desc\",project=\"$project\"}[$__interval]) or irate(mysql_global_status_innodb_data_read{desc=\"$desc\",project=\"$project\"}[5m]))/(rate(mysql_global_status_innodb_data_reads{desc=\"$desc\",project=\"$project\"}[$__interval]) or irate(mysql_global_status_innodb_data_reads{desc=\"$desc\",project=\"$project\"}[5m])))"
    }
   ]
  },
  {
   "title": "Avg Data Write Rq Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (desc) ((rate(mysql_global_status_innodb_data_written{desc=\"$desc\",project=\"$project\"}[$__interval]) or irate(mysql_global_status_innodb_data_written{desc=\"$desc\",project=\"$project\"}[5m]))/(rate(mysql_global_status_innodb_data_writes{desc=\"$desc\",project=\"$project\"}[$__interval]) or irate(mysql_global_status_innodb_data_writes{desc=\"$desc\",project=\"$project\"}[5m])))"
    }
   ]
  },
  {
   "title": "Avg Log Write Rq Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (desc) ((rate(mysql_global_status_innodb_os_log_written{desc=\"$desc\",project=\"$project\"}[$__interval]) or irate(mysql_global_status_innodb_os_log_written{desc=\"$desc\",project=\"$project\"}[5m]))/(rate(mysql_global_status_innodb_log_writes{desc=\"$desc\",project=\"$project\"}[$__interval]) or irate(mysql_global_status_innodb_log_writes{desc=\"$desc\",project=\"$project\"}[5m])))"
    }
   ]
  },
  {
   "title": "Data Written Per Fsync",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (desc) ((rate(mysql_global_status_innodb_data_written{desc=\"$desc\",project=\"$project\"}[$__interval]) or irate(mysql_global_status_innodb_data_written{desc=\"$desc\",project=\"$project\"}[5m]))/(rate(mysql_global_status_innodb_data_fsyncs{desc=\"$desc\",project=\"$project\"}[$__interval]) or irate(mysql_global_status_innodb_data_fsyncs{desc=\"$desc\",project=\"$project\"}[5m])))"
    }
   ]
  },
  {
   "title": "Log Written Per Fsync",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (desc) ((rate(mysql_global_status_innodb_os_log_written{desc=\"$desc\",project=\"$project\"}[$__interval]) or irate(mysql_global_status_innodb_os_log_written{desc=\"$desc\",project=\"$project\"}[5m]))/(rate(mysql_global_status_innodb_os_log_fsyncs{desc=\"$desc\",project=\"$project\"}[$__interval]) or irate(mysql_global_status_innodb_os_log_fsyncs{desc=\"$desc\",project=\"$project\"}[5m])))"
    }
   ]
  },
  {
   "title": "Data Read Per Row Read",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum((rate(mysql_global_status_innodb_data_read{desc=\"$desc\",project=\"$project\"}[$__interval]) or irate(mysql_global_status_innodb_data_read{desc=\"$desc\",project=\"$project\"}[5m])))/ sum((rate(mysql_global_status_innodb_row_ops_total{desc=\"$desc\",project=\"$project\",operation=\"read\"}[$__interval]) or irate(mysql_global_status_innodb_row_ops_total{desc=\"$desc\",project=\"$project\",operation=\"read\"}[5m])))"
    }
   ]
  },
  {
   "title": "Data Written Per Row Written",
   "type": "stat",
   "description": "Note: Due to difference in timing of Row Write and Data Write the value may be misleading on short intervals",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_innodb_data_written{desc=\"$desc\",project=\"$project\"}[$__interval]))/sum(rate(mysql_global_status_innodb_row_ops_total{desc=\"$desc\",project=\"$project\",operation!=\"read\"}[$__interval]))  or sum(irate(mysql_global_status_innodb_data_written{desc=\"$desc\",project=\"$project\"}[5m]))/sum(irate(mysql_global_status_innodb_row_ops_total{desc=\"$desc\",project=\"$project\",operation!=\"read\"}[5m]))"
    }
   ]
  },
  {
   "title": "InnoDB Data Bandwitdh",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_innodb_data_read{desc=\"$desc\",project=\"$project\"}[$__interval]) or irate(mysql_global_status_innodb_data_read{desc=\"$desc\",project=\"$project\"}[5m]))",
     "legendFormat": "Data Read"
    },
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_innodb_data_written{desc=\"$desc\",project=\"$project\"}[$__interval]) or irate(mysql_global_status_innodb_data_written{desc=\"$desc\",project=\"$project\"}[5m]))",
     "legendFormat": "Data Written"
    },
    {
     "expr": "avg by (service_name) ((rate(mysql_global_status_innodb_data_read{desc=\"$desc\",project=\"$project\"}[$__interval]) or irate(mysql_global_status_innodb_data_read{desc=\"$desc\",project=\"$project\"}[5m]))+ (rate(mysql_global_status_innodb_data_written{desc=\"$desc\",project=\"$project\"}[$__interval]) or irate(mysql_global_status_innodb_data_written{desc=\"$desc\",project=\"$project\"}[5m])))",
     "legendFormat": "Data Total Bandwith"
    }
   ]
  },
  {
   "title": "InnoDB Log IO",
   "type": "timeseries",
   "description": "**InnoDB I/O**\n\n_Data Writes_ - The total number of InnoDB data writes._Data Reads_ - The total number of InnoDB data reads (OS file reads)._Log Writes_ - The number of physical writes to the InnoDB redo log file._Data Fsyncs_ - The number of fsync() operations. The frequency of fsync() calls is influenced by the setting of the `innodb_flush_method` configuration option.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_innodb_log_writes{desc=\"$desc\",project=\"$project\"}[$__interval]) or irate(mysql_global_status_innodb_log_writes{desc=\"$desc\",project=\"$project\"}[5m]))",
     "legendFormat": "Log Writes"
    },
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_innodb_os_log_written{desc=\"$desc\",project=\"$project\"}[$__interval]) or irate(mysql_global_status_innodb_os_log_written{desc=\"$desc\",project=\"$project\"}[5m]))",
     "legendFormat": "Log Written"
    }
   ]
  },
  {
   "title": "InnoDB FSyncs",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_innodb_data_fsyncs{desc=\"$desc\",project=\"$project\"}[$__interval]) or irate(mysql_global_status_innodb_data_fsyncs{desc=\"$desc\",project=\"$project\"}[5m]))",
     "legendFormat": "Data Fsyncs"
    },
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_innodb_os_log_fsyncs{desc=\"$desc\",project=\"$project\"}[$__interval]) or irate(mysql_global_status_innodb_os_log_fsyncs{desc=\"$desc\",project=\"$project\"}[5m]))",
     "legendFormat": "Log Fsyncs"
    }
   ]
  }
 ]
}